# -*- coding: utf-8 -*-
"""customer support agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pu86k-xeFoQFuwqmDUFe3Q5NfcZZgfUT
"""

# W10D5 - Stateful Customer Support Agent
# Python / Google Colab

from dataclasses import dataclass, field
from typing import List, Dict
import re

print("Stateful Customer Support Agent - W10D5")

@dataclass
class ConversationState:
    """
    Stores the state of a customer's conversation.

    The agent remembers:
    - Customer name
    - Previous messages
    - Detected issue
    - Order number
    - Preferred response context
    """

    customer_name: str = ""
    order_number: str = ""
    issue: str = ""
    messages: List[Dict[str, str]] = field(default_factory=list)

    def add_message(self, role: str, content: str):
        """Add a message to conversation history."""
        self.messages.append({
            "role": role,
            "content": content
        })

    def get_history(self):
        """Return conversation history."""
        return self.messages

class CustomerSupportAgent:
    """
    A simple stateful customer support agent.

    The agent extracts information from messages and
    uses conversation history to maintain context.
    """

    def __init__(self):
        self.state = ConversationState()

    def extract_customer_name(self, message: str):
        """
        Detect simple patterns such as:
        'My name is Rahul'
        """
        match = re.search(
            r"(?:my name is|i am|i'm)\s+([A-Za-z]+)",
            message,
            re.IGNORECASE
        )

        if match:
            self.state.customer_name = match.group(1).title()

    def extract_order_number(self, message: str):
        """
        Detect order numbers such as:
        ORD12345
        ORDER12345
        """
        match = re.search(
            r"\b(?:ORD|ORDER)[- ]?\d+\b",
            message,
            re.IGNORECASE
        )

        if match:
            self.state.order_number = match.group(0).upper()

    def detect_issue(self, message: str):
        """Detect the customer's primary issue."""

        message_lower = message.lower()

        if any(word in message_lower for word in ["refund", "money back"]):
            self.state.issue = "refund"

        elif any(word in message_lower for word in ["delivery", "shipping", "late"]):
            self.state.issue = "delivery"

        elif any(word in message_lower for word in ["broken", "damaged", "defective"]):
            self.state.issue = "damaged product"

        elif any(word in message_lower for word in ["cancel", "cancellation"]):
            self.state.issue = "cancellation"

    def update_state(self, message: str):
        """Update conversation state from the latest message."""

        self.extract_customer_name(message)
        self.extract_order_number(message)
        self.detect_issue(message)

    def generate_response(self, message: str):
        """Generate a context-aware response."""

        self.update_state(message)

        name = self.state.customer_name
        order = self.state.order_number
        issue = self.state.issue

        greeting = f"{name}, " if name else ""

        if issue == "refund":
            if order:
                response = (
                    f"{greeting}I can help with the refund for order "
                    f"{order}. I will guide you through the refund process."
                )
            else:
                response = (
                    f"{greeting}I can help with your refund. "
                    f"Please provide your order number."
                )

        elif issue == "delivery":
            if order:
                response = (
                    f"{greeting}I can help check the delivery status "
                    f"for order {order}."
                )
            else:
                response = (
                    f"{greeting}I can help with the delivery issue. "
                    f"Please provide your order number."
                )

        elif issue == "damaged product":
            response = (
                f"{greeting}I'm sorry that your product arrived damaged. "
                f"I can help you with a replacement or refund."
            )

        elif issue == "cancellation":
            response = (
                f"{greeting}I can help you with your cancellation request."
            )

        else:
            response = (
                f"{greeting}I'm happy to help. "
                f"Could you provide more details about your issue?"
            )

        self.state.add_message("user", message)
        self.state.add_message("assistant", response)

        return response

    def show_state(self):
        """Display the current conversation state."""

        print("\n--- Current Conversation State ---")
        print("Customer Name :", self.state.customer_name or "Not known")
        print("Order Number  :", self.state.order_number or "Not known")
        print("Issue         :", self.state.issue or "Not known")
        print("Messages      :", len(self.state.messages))

agent = CustomerSupportAgent()

response = agent.generate_response(
    "Hi, my name is Rahul and I have a problem with my delivery."
)

print("Agent:", response)

agent.show_state()

response = agent.generate_response(
    "My order number is ORD12345."
)

print("Agent:", response)

agent.show_state()

response = agent.generate_response(
    "Can you check it for me?"
)

print("Agent:", response)

agent.show_state()

print("\n--- Conversation History ---")

for message in agent.state.get_history():
    print(f"{message['role'].upper()}: {message['content']}")

agent = CustomerSupportAgent()

print("======================================")
print(" Stateful Customer Support Agent")
print(" Type 'exit' to end the conversation")
print("======================================\n")

while True:
    user_message = input("You: ")

    if user_message.lower() == "exit":
        print("Agent: Thank you for contacting support!")
        break

    response = agent.generate_response(user_message)

    print("Agent:", response)

def test_customer_name_memory():
    agent = CustomerSupportAgent()

    agent.generate_response("Hi, my name is Rahul")

    assert agent.state.customer_name == "Rahul"

    print("PASS: Customer name memory")


def test_order_number_memory():
    agent = CustomerSupportAgent()

    agent.generate_response("My order number is ORD12345")

    assert agent.state.order_number == "ORD12345"

    print("PASS: Order number memory")


def test_issue_detection():
    agent = CustomerSupportAgent()

    agent.generate_response("My delivery is late")

    assert agent.state.issue == "delivery"

    print("PASS: Issue detection")


def test_contextual_response():
    agent = CustomerSupportAgent()

    agent.generate_response(
        "My name is Rahul and my delivery is late"
    )

    response = agent.generate_response(
        "My order is ORD555"
    )

    assert "Rahul" in response
    assert "ORD555" in response

    print("PASS: Contextual response")


def test_conversation_history():
    agent = CustomerSupportAgent()

    agent.generate_response("Hello")
    agent.generate_response("My order is ORD999")

    assert len(agent.state.messages) == 4

    print("PASS: Conversation history")


# Run all tests
test_customer_name_memory()
test_order_number_memory()
test_issue_detection()
test_contextual_response()
test_conversation_history()

print("\nAll tests passed successfully!")